// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8QaXjpRFbu-Kr2stfBztQadM3nOxh7dU',
    appId: '1:838091116520:web:e5ee80520fef026a37de5d',
    messagingSenderId: '838091116520',
    projectId: 'snuggle-tales',
    authDomain: 'snuggle-tales-e5233.firebaseapp.com',
    storageBucket: 'snuggle-tales.appspot.com',
    measurementId: 'G-49Y6FZF5RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABT6M1CyTq8MgMLd6kcUt1R1XAZXUUZEQ',
    appId: '1:838091116520:android:7a64303490583ea937de5d',
    messagingSenderId: '838091116520',
    projectId: 'snuggle-tales',
    storageBucket: 'snuggle-tales.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2ZLxsGZEPSeceJIWz9eRHnCeFeR1a2k',
    appId: '1:838091116520:ios:eb922d5e40d4d70e37de5d',
    messagingSenderId: '838091116520',
    projectId: 'snuggle-tales',
    storageBucket: 'snuggle-tales.appspot.com',
    iosBundleId: 'co.uk.flutterly.snuggleTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU2ZLxsGZEPSeceJIWz9eRHnCeFeR1a2k',
    appId: '1:838091116520:ios:7e965f526eef479e37de5d',
    messagingSenderId: '838091116520',
    projectId: 'snuggle-tales',
    storageBucket: 'snuggle-tales.appspot.com',
    iosBundleId: 'co.uk.flutterly.snuggleTales.RunnerTests',
  );
}
